# Docker Compose file for hardware (src) and website services
version: '3.8'
services:
  hardware:
    build:
      context: .
      dockerfile: src/Dockerfile
    container_name: hardware
    restart: unless-stopped
    # Add device mapping if running on real Raspberry Pi hardware
    # devices:
    #   - "/dev/gpiomem:/dev/gpiomem"
    #   - "/dev/vchiq:/dev/vchiq"
    #   - "/dev/video0:/dev/video0"
    # privileged: true
    # environment:
    #   - ENV_VAR=value

  website:
    build:
      context: ./website
      dockerfile: Dockerfile
    container_name: website
    restart: unless-stopped
    ports:
      - "5000:5000"
    # Add device mapping if running on real Raspberry Pi hardware
    # devices:
    #   - "/dev/gpiomem:/dev/gpiomem"
    #   - "/dev/vchiq:/dev/vchiq"
    #   - "/dev/video0:/dev/video0"
    # privileged: true
    # environment:
    #   - ENV_VAR=value