version: '3.8'
services:
  hardware:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: hardware
    restart: unless-stopped
    devices:
      - "/dev:/dev"
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/mem:/dev/mem"
      - "/dev/video0:/dev/video0"
      - "/dev/vchiq:/dev/vchiq"
    volumes:
      - /sys:/sys:ro
      - /proc:/proc:ro
      - /lib/modules:/lib/modules:ro
    environment:
      - LIBCAMERA_LOG_LEVEL=3
      - SPI_PATH=/app/SPI-Py
      - RFID_SPI_DEVICE=/dev/spidev0.0
    privileged: true

  website:
    image: yzhzh09/smart-fire-alert-website:latest2
    container_name: website
    ports:
      - "5000:5000"
    devices:
      - "/dev:/dev"
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/mem:/dev/mem"
    restart: unless-stopped