version: '3.8'
services:
  hardware:
    build:
      dockerfile: src/Dockerfile
      context: .
    container_name: hardware
    restart: unless-stopped
    # Uncomment the following lines if running on real Raspberry Pi hardware
    # devices:
    #   - "/dev/gpiomem:/dev/gpiomem"
    #   - "/dev/vchiq:/dev/vchiq"
    #   - "/dev/video0:/dev/video0"
    # privileged: true
    # environment:
    #   - ENV_VAR=value

  website:
    build: ./website
    container_name: website
    ports:
      - "5001:5000"
    restart: unless-stopped
    # environment:
    #   - ENV_VAR=value